name: CI
on:
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}
      - name: cargo test (ferrite)
        run: cargo test --package ferrite
      - name: cargo test (ferrite-core)
        run: cargo test --package ferrite-core
      - name: cargo clippy (ferrite)
        run: cargo clippy --package ferrite -- -D warnings -A dead-code
      - name: cargo clippy (ferrite-core)
        run: cargo clippy --package ferrite-core -- -D warnings -A dead-code
